### ISSUE TITLE
pyflakes: dictionary key 'XXX' repeated with different values

### ISSUE THREAD

**Issue by e-kwsm** [pren/poltype#20]
https://github.com/pren/poltype/blob/fb9d73f96eb70a1cc548853411ad5ec52adf694b/PoltypeModules/valence.py#L1342
https://github.com/pren/poltype/blob/fb9d73f96eb70a1cc548853411ad5ec52adf694b/PoltypeModules/valence.py#L1398
https://github.com/pren/poltype/blob/fb9d73f96eb70a1cc548853411ad5ec52adf694b/PoltypeModules/valence.py#L2484
https://github.com/pren/poltype/blob/fb9d73f96eb70a1cc548853411ad5ec52adf694b/PoltypeModules/valence.py#L2486
https://github.com/pren/poltype/blob/fb9d73f96eb70a1cc548853411ad5ec52adf694b/PoltypeModules/valence.py#L2488
https://github.com/pren/poltype/blob/fb9d73f96eb70a1cc548853411ad5ec52adf694b/PoltypeModules/valence.py#L2490
https://github.com/pren/poltype/blob/fb9d73f96eb70a1cc548853411ad5ec52adf694b/PoltypeModules/valence.py#L2492
https://github.com/pren/poltype/blob/fb9d73f96eb70a1cc548853411ad5ec52adf694b/PoltypeModules/valence.py#L2494
https://github.com/pren/poltype/blob/fb9d73f96eb70a1cc548853411ad5ec52adf694b/PoltypeModules/valence.py#L2496

**Comment by walkerbdev** [comment]
So this is an issue with poltype, where someone has manually added parameters from some old .prm file. What we really need is to map tinker type number definitions to some sort of SMART string and automatically grab parameters from prm file. Then we can have separate dictionaries for user inputs. For the redudant torsion parameters, I think the best think to do right now is just remove them and then poltype will have to regenerate for us (since I dont know which to trust).
