### ISSUE TITLE
multipole frame definition not general in poltype

### ISSUE THREAD

**Issue by leucinw** [pren/poltype#28]
1. Poltype frame definition is not "robust", for example, it defines "**N on Methylamine as Z-bisec**" but  "**N on Ethylamine is Z-only**", where Z-bisec should be better (same as Methylamine)

2. Considering using the poledit-defined frames. 

@bdw2292 we should fix this.

**Comment by jayponder** [comment]
Hi Everyone,

I’ll reply to this via your emails instead of Github so everyone sees it.

This is just the same old amine problem that we have had with AMOEBA for years..

Using Z-Only is always “safe”. Using “Z-Bisect” is “better”, but is undefined when the amine is exactly flat, and has a discontinuity when the amine passes through flat the flips from one pyramidal structure to the other. I’ve been thinking about and discussing with people for a long time. The “correct” solution is to scale the multipoles on the nitrogen based on how much the nitrogen is out-of-plane, but that’s “hard” and messy. Short of that, I think we should only use “Z-Bisect” at pyramidal nitrogens if we are sure they will not invert on the time scale we plan to simulate.

Ammonia and simple alkyl amines do not invert that frequently at room temperature. But they can, especially at high temperature. Lots of other amines and aniline nitrogens in ligands and drugs invert fairly easily.

We need to adopt a standard policy for this.

I’m happy to make POLEDIT do whatever we finally decide, and I can easily make it “robust”. The choice of the local frame should be done in POLEDIT, I think, and not in the automated parameterization protocol.

Comments?

Best, Jay

> On Jul 20, 2020, at 11:16 AM, Chengwen Liu <notifications@github.com> wrote:
> 
> 	• Poltype frame definition is not "robust", for example, it defines "N on Methylamine as Z-bisec" but "N on Ethylamine is Z-only", where Z-bisec should be better (same as Methylamine)
> 
> 	• Considering using the poledit-defined frames.
> 
> @bdw2292 we should fix this.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

--
Jay W. Ponder                          Phone:  1-314-935 4275
Chemistry, Campus Box 1134             Fax:    1-314-935 4481
Washington University in St. Louis
One Brookings Drive                    Email:  ponder@dasher.wustl.edu
St. Louis, Missouri 63130  USA         WWW:    http://dasher.wustl.edu/

**Comment by jayponder** [comment]
Thanks Jay for the explanation.

Is it possible to store two sets of frames for the atom at the pyramidal
site? If all the atoms are in a plane, we switch to the second frame for
that atom.

Chengwen

**Comment by jayponder** [comment]
Switching during MD cause discontinuity in energy/force. Making the multipoles depending on OOP angle will make the force complicated.

To be safe, I suggest we use Z-only for N (N C 0); use Z-then-x for H (H N C). What’s missed on N can be compensated by H.

**Comment by leucinw** [comment]
I compared the quality of the fitted multipoles using different frames. 
- For MeNH2: **0.29** (Z-only for N) vs **0.18** (Z-bisect for N). 
- For EthNH2 and PropNH2, different frames do not affect the RMSPD.
It is probably good enough to use Z-only frame (and safer).

**Comment by jayponder** [comment]
Hi Chengwen, et al.,

I was about to do the same thing.. To make a more dramatic and cleaner test, I’ll try CH2F. That molecule is pyramidal like ammonia, and I will see which local frame does best for the pyramidal structure. I’ll also check how well the same multipoles describe the planar structure for CH2F. I’ll let you know what I find.

And just for completeness, there is a third local frame option, which is to use Bisector on the nitrogen. This is probably closer to Z-Only than to Z-Bisect. Like Z-Only it does not really allow the local frame to describe the “lone pair” direction on the nitrogen. It would still force the y-dipole at nitrogen to be zero. But unlike Z-Only it would allow separate xx- and yy-quadrupole moments. I’ll try all three local frames for NH2F.

Of course, a fourth possibility is to generally put an explicit dummy lone pair on nitrogen. If done with standard angle parameters this would not allow inversion at the nitrogen. And having dummy sites causes all sorts of other problems throughout Tinker that I’d prefer to avoid.

As I indicated before, I believe the “correct” solution is to make the nitrogen multipoles a function of nonplanarity at the nitrogen. This is roughly similar to the kind of “charge flux” mechanism you folks added, but would probably (?) need to be extended to dipoles and quadrupoles for this case. I’ve attached a related paper from Sam Krimm’s group that studied this problem for the (easier?) case of amide nitrogens.

Best, Jay

> On Jul 20, 2020, at 1:32 PM, Chengwen Liu <notifications@github.com> wrote:
> 
> I compared the quality of the fitted multipoles using different frames.
> 
> 	• For MeNH2: 0.29 (Z-only for N) vs 0.18 (Z-bisect for N).
> 	• For EthNH2 and PropNH2, different frames do not affect the RMSPD.
> It is probably good enough to use Z-only frame (and safer).
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

--
Jay W. Ponder                          Phone:  1-314-935 4275
Chemistry, Campus Box 1134             Fax:    1-314-935 4481
Washington University in St. Louis
One Brookings Drive                    Email:  ponder@dasher.wustl.edu
St. Louis, Missouri 63130  USA         WWW:    http://dasher.wustl.edu/

**Comment by pren** [comment]
For static structures the Z only (N C) or bisector (N -H -H) may be similar but I prefer the Z only one because again H can pick up what is missing on N. If use bisector, the N C component (probably dominant) will be missing.
