### ISSUE TITLE
different parameters with updated poltype

### ISSUE THREAD

**Issue by ahmedo047** [pren/poltype#64]
Hi,

I recalculated the benzene parameters with the updated poltype. It's interesting that old and updated poltype produce different parameters of benzene (see attached file). Is there a bug in the updated poltype?
[benzene.zip](https://github.com/pren/poltype/files/5589201/benzene.zip)

**Comment by walkerbdev** [comment]
Hi,
Yes, there is a new algorithm for grabbing parameters from amoba09.prm
file, you will observe some differences. I think what you have in your
first key file is fine, the valence parameters from benzene and that
molecule are very similar. When two molecules are same number of atoms and
the algorithm is matching part of your input molecule to both of those
molecules, there is an ambiguity if the matching length between the two
molecules being matched in amoeba09.prm file is the same. I have added an
additional "filter" that looks at differences in each element between input
molecules and what is being matched to. So effectively, you will see
parameters matching from benzene if you look in the key file I have
attached bellow instead of pyridinium.

**Comment by ahmedo047** [comment]
Hi,

You haven't attached any file.
You say the results of the present/updated version of poltype for benzene aren't OK, right? That means I shouldn't use the updated poltype for parameterization of molecules?

**Comment by walkerbdev** [comment]
[benzene.key_4.txt](https://github.com/pren/poltype/files/5592255/benzene.key_4.txt)
My bad, attaching from outlook does not seem to work. So the original key file you had is fine, the molecules parameters that were being transferred for bond,angle,torsion etc were all very similar to benzene. I have however, added an additional filter to get as "close as possible" to the input molecule. I dont expect results of simulation to change that much.
