### ISSUE TITLE
Amoeba13 Support?

### ISSUE THREAD

**Issue by rubber-duck-debug** [pren/poltype#67]
Hey there, I've managed to successfully run your code for a few small molecules - it looks great!

Firstly I'd just like to mention one small issue I've noticed. If I have the following in the run directory:

file.xyz (in normal XYZ format, to be converted to sdf via openbabel/rdkit)
file.sdf
poltype.ini

file.xyz will not get overwritten with a tinker formatted XYZ file, so when it comes to fitting against the electrostatic potential, the tinker "potential" program will fail as it will read file.xyz. Poltype seems to instead write this tinker XYZ file as file.xyz_2, but it doesn't read from it for the potential fitting part.

Not having this .xyz file there in the directory resolves this problem, though, and file.xyz is correctly created in tinker XYZ format.

Secondly to the point of this post, I was wondering if it was possible to use poltype in conjunction with the Amoeba13 parameter set? I'm interested in using OpenMM, and it seems like that the 2013 parameter set is the one that OpenMM recommends.

many thanks!

**Comment by walkerbdev** [comment]
Hi,

Yes, the tinker program will read for any xyz_# files in the directory
(.xyz is like .xyz_1) and then any tinker xyz files produced afterwords
will always be xyz_# > previous largest #. So what is happening is that the
program poltype is expecting a certain xyz_# but does not get that because
all the xyz file numbers have been shifted up a number.

For amoeba13.prm, you can just source the parameter file in your key file
with the keyword "parameters path_to_parameterfile". See
https://dasher.wustl.edu/tinker/downloads/tinker-guide.pdf  for more
details.

I can remove all *.xyz* files as a first step to avoid such issues.

- Brandon
