### ISSUE TITLE
Not detecting scratch files

### ISSUE THREAD

**Issue by EnriqueVqz92** [pren/poltype#87]
Hello. I got the following issue after trying to run the poltype command. The error message is:

FileNotFoundError: [Errno 2] No such file or directory: '/scratch/jv0299'

I have changed the directory path to ensure that is calling the right directory and it won't work. I did not have any problem with the installation of Python packages, just when I tried to run poltype program.
[poltype_inputs.zip](https://github.com/pren/poltype/files/6186294/poltype_inputs.zip)

**Comment by mquevill** [comment]
By default, if nothing is specified, POLTYPE will try to use `/scratch`. However, environment variables are also detected within POLTYPE. If you have `GAUSS_SCRDIR` defined for Gaussian or `PSI_SCRATCH` for Psi4, it will attempt to use those directories.

Your input files do not specify a `scratchdir`, so have you set either of these environment variables? Since you have not specified anything relating to Gaussian, check if `PSI_SCRATCH` is set.

If you want to use the directory at `/scratch/jv0299`, you need to make sure this directory already exists before running POLTYPE. If it does not exist yet, please run the following command to create it:
```bash
mkdir -p /scratch/jv0299
```

[In addition, the process should be able to write to that directory. That is, make sure the user has read/write permissions in that location.]

**Comment by mquevill** [comment]
Looking at your `run_poltype.sh` script, you are defining `PSI_SCRATCH`. Does this directory exist?

In addition, you define things for Gaussian. But since you aren't setting `use_gaus` or `use_gausoptonly`, it will use Psi4 only.

However, there is a quirk of the code:
https://github.com/pren/poltype/blob/a772dd9a967f1f27379d99c2a6bd4b55c22a30e0/PoltypeModules/poltype.py#L706-L715
Since you have `GAUSS_SCRDIR` defined, it is using whatever you define for `GAUSS_SCRDIR`, even for Psi4.
