### ISSUE TITLE
.gdmain file issue with poltype2

### ISSUE THREAD

**Issue by DanieleLoco** [pren/poltype#90]
Hello!

I'm running some test with poltype2 using psi4 and it seems to me that there is an issue in generating the input file for GDMA. In my test Poltype just stops the process while waiting for Psi4 to terminate:

...
Fri Apr 23 22:05:59 2021 All jobs have terminated 
Fri Apr 23 22:05:59 2021 Normal termination: logfile=~/poltype/Examples/test2/methane-opt_1.log path=~/poltype/Examples/test2
Fri Apr 23 22:06:29 2021 All jobs have terminated 
Fri Apr 23 22:06:29 2021 Calling: Psi4 Gradient for DMA
Fri Apr 23 22:06:29 2021  Calling: cd ~/poltype/Examples/test2 && psi4 methane-dma.psi4 methane-dma.log path =~/poltype/Examples/test2
Fri Apr 23 22:06:35 2021 Waiting on ~/poltype/Examples/test2/methane-dma.log for termination 

On the other hand Psi4 calculation

molecule { 
0 1
C 0.000666742318 -0.000106001132 -0.000760232728
H -0.568376898990 -0.732578372275 -0.306057419309
H -0.392173362037 0.849443006590 -0.279001897301
H 0.057084805866 -0.023467742950 0.973943565620
H 0.895526668603 -0.092134754044 -0.379832288158
} 
memory 700MB
set_num_threads(1)
psi4_io.set_default_path("~/anaconda3/scratch/Psi4-methane")
set freeze_core True
set PROPERTIES_ORIGIN ["COM"]
set cubeprop_tasks ['esp'] 
E, wfn = energy('mp2/6-311G**',properties=['dipole'],return_wfn=True)
cubeprop(wfn) 
fchk(wfn, "methane-dma.fchk")
gdma(wfn,"methane_3D.gdmain")
clean()

seems to correctly terminate and it produces the fchk, but the process stops since no gdmain is found (I think).
I tried to have a look at the portion of the code which menages this task and it did seem to me to see a particular problem in there. I guess could be more something on my side, in the environment setting?

Thank you in advance for any help,

Daniele

**Comment by walkerbdev** [comment]
Hello,

We noticed this issue with psi4 last week. I turned off psi4 GDMA and switched back to external compiled executable and it worked fine, did not make any changes to input files for gdma.
________________________________
From: DanieleLoco ***@***.***>
Sent: Monday, April 26, 2021 2:54:41 AM
To: pren/poltype ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [pren/poltype] .gdmain file issue with poltype2 (#90)


Hello!

I'm running some test with poltype2 using psi4 and it seems to me that there is an issue in generating the input file for GDMA. In my test Poltype just stops the process while waiting for Psi4 to terminate:

...
Fri Apr 23 22:05:59 2021 All jobs have terminated
Fri Apr 23 22:05:59 2021 Normal termination: logfile=/poltype/Examples/test2/methane-opt_1.log path=/poltype/Examples/test2
Fri Apr 23 22:06:29 2021 All jobs have terminated
Fri Apr 23 22:06:29 2021 Calling: Psi4 Gradient for DMA
Fri Apr 23 22:06:29 2021 Calling: cd /poltype/Examples/test2 && psi4 methane-dma.psi4 methane-dma.log path =/poltype/Examples/test2
Fri Apr 23 22:06:35 2021 Waiting on ~/poltype/Examples/test2/methane-dma.log for termination

On the other hand Psi4 calculation

molecule {
0 1
C 0.000666742318 -0.000106001132 -0.000760232728
H -0.568376898990 -0.732578372275 -0.306057419309
H -0.392173362037 0.849443006590 -0.279001897301
H 0.057084805866 -0.023467742950 0.973943565620
H 0.895526668603 -0.092134754044 -0.379832288158
}
memory 700MB
set_num_threads(1)
psi4_io.set_default_path("~/anaconda3/scratch/Psi4-methane")
set freeze_core True
set PROPERTIES_ORIGIN ["COM"]
set cubeprop_tasks ['esp']
E, wfn = energy('mp2/6-311G**',properties=['dipole'],return_wfn=True)
cubeprop(wfn)
fchk(wfn, "methane-dma.fchk")
gdma(wfn,"methane_3D.gdmain")
clean()

seems to correctly terminate and it produces the fchk, but the process stops since no gdmain is found (I think).
I tried to have a look at the portion of the code which menages this task and it did seem to me to see a particular problem in there. I guess could be more something on my side, in the environment setting?

Thank you in advance for any help,

Daniele
