### ISSUE TITLE
Torsions of small non-aromatic rings and quarternary carbon atoms in rings

### ISSUE THREAD

**Issue by D16ERG** [pren/poltype#95]
Dear all,

During the parameterization of delta 24 Ergosterol, I noticed that this molecule suffers from
missing torsions. For this reason I experimented with smaller, comparable systems. Through
the SMARTS keys, I noticed that quarternary carbons atoms in (fused) rings results in missing
torsions. While bare cycloalkanes display a somewhat similar issue; I don't believe this was the cause of these missing torsions. IIRC the latter issue was caused by an inactive fragmenter 
(<25 atoms). 

![Delta24Ergosterol](https://user-images.githubusercontent.com/79671816/127532564-a300e648-d3b8-4b32-be20-ad6864f9f6e4.png)

![testmolecule](https://user-images.githubusercontent.com/79671816/127532591-5dd146f3-27b1-4b5c-92a8-f703f57e258e.png)

On another note, I would like to ask what skills it takes to properly grasp 
Poltype. Currently I am finishing my BSc. in general chemistry. Herein I 
did follow the quantum and physical chemistry courses.  As a reference 
I currently own "The Theory of Intermolecular Forces" by Anthony Stone.
In addition to this I do realize Poltype heavily relies on Python. Despite 
this; Poltype seems to be particularly challenging to grasp, let alone develop. 
(this latter comment is not meant in any bad way)

Kind regards,

Didier

**Comment by walkerbdev** [comment]
Hello,

Please attach a link of all input and output files and I can take a look. For now can just read original poltype publications and the online documentation and let us know if anything is confusing. 

- Brandon

**Comment by D16ERG** [comment]
Dear Brandon,

All input and output of the latter molecule have been compressed into the following zip-file:
https://wetransfer.com/downloads/6742f6cf8be571e278e3b59a21ba13cd20210729174117/f1f8d7

Kind regards,

Didier

**Comment by walkerbdev** [comment]
When I click on the link it in the website location it just says "
http://url/" and says this site cannot be reached.

**Comment by D16ERG** [comment]
I just updated the link. Regarding what I don't understand is the following example:

# Transferring from ['Alkane -H2C-', 'Alkane -CH2-', 'Alkane -CH2-', 'Alkane -H2C-']

# Fitted from Fragment  SMARTS [#6](-[#6](-[H])(-[H])-[H])(-[#6](-[#6](-[H])(-[H])-[H])(-[H])-[H])(-[H])-[H] torsion atom indexes = 7,2,0,4 with smarts torsion indices 12,6,1,14 from fragment 13_1_Index_0.mol
# torsion % [#6](-[#6](-[H])(-[H])-[H])(-[#6](-[#6](-[H])(-[H])-[H])(-[H])-[H])(-[H])-[H] % 12,6,1,14 % 0,0,0.299

I do grasp the SMART format of describing molecules. What I did not understand were the torsion atom indices and the smarts atom indices. Especially the "0" in this excerpt "torsion atom indexes = 7,2,0,4 " is confusing.

**Comment by leucinw** [comment]
I believe you should get rid of https://

**Comment by pren** [comment]
https://we.tl/t-7K3pdgzT5a
this worked for me

**Comment by walkerbdev** [comment]
Yes thank you the first time did not work but after updating the link works
fine.

# Fitted from Fragment  SMARTS
[#6](-[#6](-[H])(-[H])-[H])(-[#6](-[#6](-[H])(-[H])-[H])(-[H])-[H])(-[H])-[H]
torsion atom indexes = 7,2,0,4 with smarts torsion indices 12,6,1,14 from
fragment 13_1_Index_0.mol
# torsion %
[#6](-[#6](-[H])(-[H])-[H])(-[#6](-[#6](-[H])(-[H])-[H])(-[H])-[H])(-[H])-[H]
% 12,6,1,14 % 0,0,0.299
torsion 415 401 405 413 0 0.0 1 0 180.0 2 0.299 0.0 3

Torsion atom indexes are like if you open molecule in pymol and start atoms
with 0 based index, which atoms are in torsion. Smarts torsion indices are
like which atoms in smart string counting left to right starting from 1.

**Comment by walkerbdev** [comment]
So I know it will say in poltype.log parameters are missing, then will fit
or assign default values but your final key file is not "missing" any
parameters. Can check this via analyze tinker program with xyz and key file.

**Comment by D16ERG** [comment]
Could I have a faulty installation?
When I restart poltype from the directory I just sent; I only receive a ValueError:

_Poltype -- Polarizable atom typer of small molecules for the AMOEBA polarizable force field

Please cite:
Wu, J.C.; Chattree, G.; Ren, P.Y.; Automation of AMOEBA polarizable force field 
parameterization for small molecules. Theor Chem Acc. 

Version 2.3.1 May 2021

Copyright (c)  Johnny Wu, Gaurav Chattree, Brandon Walker, Matthew Harger and Pengyu Ren 2019

All Rights Reserved


ValueError: torsion parameters are all zero torsion 401 407 402 409 0 0.0 1 0 180.0 2 0 0.0 3
 path =/home/didier/Desktop/ABring_

**Comment by walkerbdev** [comment]
Thank you, the error you see gets piped to standard output and not into the
poltype.log so I would not have seen it without running myself. The issue
is rather complicated to explain, there is a section in the docs
(databaseparser.py) regarding treatment of torsion on a ring and what is
assigned via an array of hybridizations (SP3/SP2 etc) for each atom of the
torsion, there have been some "special" cases I have run across
involving torsion between rings that complicates things. Our rules are
supposed to decide if the ring is "non-aromatic enough" for its own
fragment or if needs to be transferred torsion from alkane/benzene. Easy
case is all 4 atoms on 1 ring, another case is like in adenine-diphosphate,
where lets say 3 atoms are on sugar ring (SP3), but last atom is SP2 on
adenine, then if you just use your array of hybridizations following the
rules in the docs you would not be able to make its own fragment for
torsion parameters, so what I have done previously is essentially only
include the atoms on that first ring where the rotatable bond is. In your
case, is also a special case where there is non-aromatic ring attached to
mostly aromatic. Essentially I believe the program just saw the first two
on non-aromatic ring and then thinks its able to make its own fragment,
however this fragment was not made ( i have another part of program that
checks for which torsions are viable for fragments), then since the
parameters were set to 0 in first key file (set to 0 in order to fit), but
not fitting occured then there is an error at the end...

Anyway, for now I have temporarily changed it to not remove any atoms in
the hybdrization array and now alkane parameters will be transferred since
the middle bond has one SP3 and one SP2. Just update program and delete
key_4 and .key_5 and restart.


   1. If b aromatic and c not aromatic or (b non-aromatic and c aromatic).
      1. If H-X-X-X transfer from H-C-C-C
      2. If H-X-X-H transfer from H-C-C-H
      3. If X-X-X-X transfer from C-C-C-C

**Comment by D16ERG** [comment]
Just read your comment. The updated code is running now.

**Comment by D16ERG** [comment]
Dear Brandon and Pengyu,

Thank for your time and efforts! The parameterization of the above fragment ran just fine.
I tried piecing together a solution with the current extensive documentation. Unfortunately
this is well above my pay grade. 

For those who are interested: the parameterizations will be incorporated into a 
QM/MM setup. This setup features the progams Autodock, Tinker, Poltype2, 
BAGEL and Newton-X to simulate the photochemistry of a host-guest complex 
which features a vitamin D. Since the molecules involved are moderately big; 
not every atom is involved in the actual photochemistry of the excited states. 
Hence the use of QM with BAGEL and MM with Tinker.

![Docked cyclodextrin 2](https://user-images.githubusercontent.com/79671816/127554159-12bfe02a-7eb2-4ef8-8556-3b8da85c94da.png)

This setup was inspired by the following paper:
Catalyzed Thermal Isomerization between Previtamin D3 and Vitamin D3 via β-Cyclodextrin Complexation
DOI:https://doi.org/10.1074/jbc.270.15.8706

Kind regards,

Didier
