### ISSUE TITLE
Cyclopentane all-carbon ring torsions

### ISSUE THREAD

**Issue by D16ERG** [pren/poltype#96]
Dear all,

While parameterizing delta24-Ergosterol, I stumble on a ValueError for one of the final fragments. 
This fragment, is fragment 3_2_3_8_Index_0 in the linked poltype job below.
https://we.tl/t-q4ZsHwjwQQ
Most parameters are processed uneventfully with the exception of the cyclopentane ring-torsions.
When cyclopropane is parameterized as a fragment of a larger molecule; poltype returns a "Torsion did not reach target dihedral! " error.

Trying to parameterize cyclopentane as a loose molecule, results in a completed poltype run. Unfortunately these runs are unsuccessful because analyze reports undefined torsion parameters in final.key. I have already tried updating poltype to today its revision. Unfortunately these changes address other issues.

Kind regards,

Didier

**Comment by walkerbdev** [comment]
Hello,
Thanks for catching this. So this is gonna be long and im gonna try to simplify as best as possible.
1)	There was a keyword in your input file regarding non-aromatic torsion scanning, this was originally used a long time ago to deal with a weird case in the fragmenter module where the whole molecule was one giant ring and I had to inform poltype that it was “okay” to look at bonds in this massive ring and use for fragmenter. I have removed this keyword it does not do anything now and it would not have applied to your situation even with the older code.
2)	The keyword for refining non-aromatic torsions was turned on. There were two main issues here, the first being the error you saw (torsion not reaching target dihedral angle). Essentially this was due to not the “correct torsion restraints” being used in input keyfile. I have employed a new strategy that basically attempts to cover as many atoms as possible in each “torsion” on ring that is being puckered, without overlapping with other restraints. This is difficult to visualize without opening up the fragment you mentioned in pymol, but basically the idea is that we chose two neighboring bonds (for 5 atom non-aromatic ring), that need to be puckered and if we chose just the restraints based on those torsion in the ring, quite a few atoms would be overlapping (3 would be) (restraints fighting a bit with each other). The minimum case is just having one atom in common between two bonds in the ring for two torsion restraints, this is accomplished by choosing a and d in a-b-c-d such that a and d may not be on the ring (b-c is still on the ring). The second issue was that previously this keyword for refining non-aromatic torsions did not always fit the “desired missing torsion”. This is because the algorithm takes two missing in the ring, then it picks two neighboring in the ring to pucker, however the ones that are being used to pucker are the torsion parameters that were previously being fit whereas now I believe that I have patched this ( still running QM but will find out soon enough). So previously when this keyword was used most likely the parent molecule was grabbing torsion from this ring fragment that was not being fit (it was grabbing torsion that was transferred from our database). This option for refinement is also more expensive 5^n grid points (in this case 5^2=25) instead of just 12 for each torsion like normal 1D scans. The default behavior is instead of puckering to make a fragment of that ring and do a 1D scan around that torsion. So just as a general rule of thumb for right now default options in poltype are “safer”. They have been tested much more…..
3)	I notice a few other smaller issues, one being that typically in fragments we will try to preserve any aromatic ring system attached to torsions that are being fit. However, this molecule is a case not dealt with much before where part of some of the rings are “flat” SP2 and others are SP3. So the resulting fragment looks a bit funny, an appendage on the ring being puckered has the “flat” part of the neighboring ring. I have modified the behaviour to only include if all atoms in ring are flat. Sometimes those ring systems can be important for electron density near the torsion of interest. The last issue was that previously with this keyword for nonaromatic ring refinement, it would pucker the ring but also do QM for any other missing torsions in that molecule. I have modified this to only do QM for the ring puckering. 
4)	So to summarize, since with new version the fragments will be different, your easiest fix is to just delete the Fragments folder and restart (unless you are able to tell which fragments are changed with new behaviour and only delete those subfolders…). Also better to just not use this refinement keyword until I have done some final testing.

**Comment by D16ERG** [comment]
Dear Brandon,

Just read and processed your assessment of the issues. It took me a while to grasp these subtle difficulties. I removed the keyword "allownonaromaticringscanning" from poltype.ini and also noticed this change in poltype. Your high-level explanation of the issues at hand is excellent. I now understand that due to conflicting (or rather overlapping) restraints; adjacent ring(!)-bonds can have trouble reaching their target dihedrals in small rings. Through ValueErrors; such overlaps prevent poltype from successfully puckering rings and fitting torsions. Because default settings initially failed; I enthusiastically used to experimented with different ring-scanning and refinement settings. Now I know that this is not such a good idea. Knowing this; I will run delta24-Ergosterol its parameterization with the default settings as summarized. On another I stumbled upon a Psi4 setting which seemed to resolve some difficult fitting and optimization cases.

     FAIL_ON_MAXITER (Fail if we reach maxiter without converging?)
           Type: boolean
            Default: true

   https://psicode.org/psi4manual/master/autodoc_glossary_options_c.html#term-FAIL_ON_MAXITER-SCF

I plugged this option into optimization.py and torsiongenerator.py with some success. I only need to recall which molecular fragments actually needed this setting after failing to converge.

Kind regards,

Didier

**Comment by D16ERG** [comment]
Dear all,

After rerunning the above job; I encountering a similar error with today its revision of poltype 2.
The fragment in question involves a cyclic structure. This structure encounters the above issue 
of not reaching the target dihedral angle. This dihedral angle seems to be within the ring. 

[5_9_Index_0.tar.gz](https://github.com/pren/poltype/files/7002506/5_9_Index_0.tar.gz)


Kind regards,
Didier

PS: I transferred this issue to the new repository at:
https://github.com/TinkerTools/poltype2/issues/1
